### PR TITLE
Handle not json response

### PR DESCRIPTION
**Pull request by borovik96**
So will be no unhandled exeptions #97

### CODE REVIEW

**Comment by pedrobranco** [comment]
@borovik96  Can you please provide the body of the bad response?

**Comment by borovik96** [comment]
Actually, I do not have access to them, because of lib throws an unhandled error on production

**Comment by pedrobranco** [comment]
> Actually, I do not have access to them, because of lib throws an unhandled error on production

You should check what's the actual Bitcoin daemon response before wrapping the code in any try catch.

Either way, as the code proposal is right now is a NACK.

**Comment by pedrobranco** [comment]
Closing due to inactivity.

**Comment by sbryant31** [comment]
why do you close this, it's important

**Pull request closed without merging**
